services:
  questify-app:
    image: neto002/questify
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge