services:
  questify-app:
    image: neto002/questify
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - app_network
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questify
    networks:
      - app_network
networks:
  app_network:
    driver: bridge