name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Login to Docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker container
        run: |
          docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/questify

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Update Repo
        run: |
          if [ ! -d "questify"]; then
            git clone git@github.com:Neto002/questify.git
          else
            cd questify && git pull
          fi

      - name: Pull Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/questify
          docker-compose down
          docker-compose up -d
